import Head from 'next/head'
import '../app/globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* Tambahkan tag HTML lainnya sesuai kebutuhan */}
      </Head>
      <Navbar />
          <Component {...pageProps} />
          <Footer />
    </div>
  )
}

export default MyApp
