import Head from 'next/head'
import '../app/globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight:'400' })


function MyApp({ Component, pageProps }) {
  return (
    <div className={poppins.className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
          <Component {...pageProps} />
          <Footer />
    </div>
  )
}

export default MyApp
